// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB_3c2uQuTGw14avDTt4vP4-mfCPmuII4',
    appId: '1:416973749351:web:8cba2aabf21ef67dc1a8c2',
    messagingSenderId: '416973749351',
    projectId: 'servisso',
    authDomain: 'servisso.firebaseapp.com',
    storageBucket: 'servisso.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMQyjk4WdnCGohI3JsoBP-2Ri_7SSQw9w',
    appId: '1:416973749351:android:1e6e1c9f20b26566c1a8c2',
    messagingSenderId: '416973749351',
    projectId: 'servisso',
    storageBucket: 'servisso.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO5Wp0W-OCvoMX7rESGi2RiC8ufQyJpGE',
    appId: '1:416973749351:ios:847b78c65cd99ea5c1a8c2',
    messagingSenderId: '416973749351',
    projectId: 'servisso',
    storageBucket: 'servisso.appspot.com',
    iosBundleId: 'com.servisso.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO5Wp0W-OCvoMX7rESGi2RiC8ufQyJpGE',
    appId: '1:416973749351:ios:847b78c65cd99ea5c1a8c2',
    messagingSenderId: '416973749351',
    projectId: 'servisso',
    storageBucket: 'servisso.appspot.com',
    iosBundleId: 'com.servisso.app',
  );
}
